### User authenticates with valid email and password
# @no-cookie-jar
POST {{baseUrl}}/api/users/login
Content-Type: application/json

{
  "email": "{{johnEmail}}",
  "password": "{{password}}"
}

### User authenticates with invalid email
POST {{baseUrl}}/api/users/login
Content-Type: application/json

{
  "email": "{{johnEmail}}asdf",
  "password": "{{password}}"
}

### User registers
POST {{baseUrl}}/api/users/

### User logs out
POST {{baseUrl}}/api/users/logout

### User gets their profile
GET {{baseUrl}}/api/users/profile

### User updates their profile
PUT {{baseUrl}}/api/users/profile

### Admin gets all users
GET {{baseUrl}}/api/users/admin

### Admin gets a user by id
GET {{baseUrl}}/api/users/:id

### Admin deletes a user
DELETE {{baseUrl}}/api/users/:id

### Admin updates a user
PUT {{baseUrl}}/api/users/:id


